name: Deploy Authentik

on:
  push:
    branches:
      - main

jobs:

  prepare-env:
    runs-on: self-hosted
    steps:
      - name: Create .env on server
        run: |
          # Путь должен совпадать с тем, что в шаблоне (из vars.DEPLOY_PATH)
          TARGET_DIR="${{ vars.DEPLOY_PATH }}/Authentik"
          mkdir -p $TARGET_DIR
          echo "PG_PASS=${{ secrets.AUTHENTIK_PG_PASS }}" > $TARGET_DIR/.env
          echo "AUTHENTIK_SECRET_KEY=${{ secrets.AUTHENTIK_SECRET_KEY }}" >> $TARGET_DIR/.env
          echo "AUTHENTIK_ERROR_REPORTING__ENABLED=true" >> $TARGET_DIR/.env

  call-deploy:
    uses: leoserverteam/DevOpsTemplates/.github/workflows/onlycompose.yml@main
    with:
      project_name: "Authentik"
    secrets:
      # Прокидываем секреты напрямую, если шаблон их ожидает,
      # либо они подтянутся через secrets: inherit
      inherit

  call-nginx:
    needs: call-deploy
    uses: leoserverteam/DevOpsTemplates/.github/workflows/deploynginx.yml@main
